### ISSUE TITLE
Repository should be renamed to "SnortBlocklistImporter"

### ISSUE THREAD

**Issue by TheAlanNix** [CiscoSE/TalosBlacklistImporter#4]
@cmlccie or @ccosby - can you please rename this repo to "SnortBlocklistImporter"?

@kywinter

**Comment by finchy** [comment]
Yes. Please rename repo.

**Comment by ccosby** [comment]
It's done.

**Comment by finchy** [comment]
Thank you much.

**Comment by kyle-winters** [comment]
Thank you! I will resync with code exchange  now

**Comment by kyle-winters** [comment]
Ugh I also don't have permissions to do this, since @TheAlanNix still owns it inside the devnet code exchange... Alan are you still able to resync the project inside of the devnet dashboard?

**Comment by TheAlanNix** [comment]
Unfortunately not, I think I submitted it using my CCO ID - which is obviously no longer enabled.

**Comment by kyle-winters** [comment]
I'll work with DevNet to get it resync'd
